echo "*******************************************************************************"
echo "* This file is part of fhlow (fast handling of a lot of work), a working"
echo "* environment that speeds up the development of and structures FPGA design"
echo "* projects."
echo "* "
echo "* Copyright (c) 2011-2016 Michael Roland <michael.roland@fh-hagenberg.at>"
echo "* "
echo "* This program is free software: you can redistribute it and/or modify"
echo "* it under the terms of the GNU General Public License as published by"
echo "* the Free Software Foundation, either version 3 of the License, or"
echo "* (at your option) any later version."
echo "* "
echo "* This program is distributed in the hope that it will be useful,"
echo "* but WITHOUT ANY WARRANTY; without even the implied warranty of"
echo "* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the"
echo "* GNU General Public License for more details."
echo "* "
echo "* You should have received a copy of the GNU General Public License"
echo "* along with this program.  If not, see <http://www.gnu.org/licenses/>."
echo "*******************************************************************************"

vsim -do ../../../../fhlow/simQuestasim/CompSim.do
